apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: springboot-pipeline
  labels:
    tekton.dev/pipelines: default/springboot-pipeline
spec:
  params:
    - name: repo_url
      type: string
    - name: image
      type: string
    - name: deployment_manifest
      type: string
    # - name: helm_chart
    #   type: string
    - name: namespace
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: repo_url
          value: $(params.repo_url)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-app
      taskRef:
        name: build-app
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: docker-build-and-push
      taskRef:
        name: docker-build-and-push
      params:
        - name: image
          value: $(params.image)
      runAfter:
        - build-app
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: deploy-to-aks
      taskRef:
        name: deploy-to-aks
      params:
        - name: deployment_manifest
          value: $(params.deployment_manifest)
        # - name: helm_chart
        #   value: $(params.helm_chart)
        - name: namespace
          value: $(params.namespace)
        - name: image
          value: $(params.image)
      runAfter:
        - docker-build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace
