apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-test
  namespace: default
  labels:
    tekton.dev/pipelines: default/springboot-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic-test
  template:
    metadata:
      labels:
        app: pet-clinic-test
    spec:
      containers:
        - name: pet-clinic-test
          image: idpdeveacr.azurecr.io/pet-clinic-test:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-test
  namespace: default
spec:
  selector:
    app: pet-clinic-test
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer